export const I18N = {
  ar: {
    dir: 'rtl',
    bar1: 'وداعاً لحيرة القياس.. نضمن لك المقاس المثالي أو الاستبدال مجاناً ✅',
    bar2: ' مقاسات خاصة من 2XL حتى 7XL 📏      شحن مجاني للطلبات الكبيرة 🚛',
    navShop: 'المتجر', navAbout: 'عن SizeMe', navContact: 'تواصل',
    tagline: ' للقياسات الخاصة',
    heroKicker: '   أناقة تناسب كل المقاسات.',
    heroTitle: 'الوجهة الأولى في العراق للمقاسات الخاصة',
    heroSub: 'تشكيلات حصرية  من  دور  الازياء  العالمية  تلائم  اسلوب  حياتك',
    videoTitle: 'رؤيتنا', videoHint: 'ضع الفيديو في video/brand-mission.mp4',
    aboutKicker: 'حرفتنا',
    aboutTitle: 'متخصصون بملابس الماركات الحصرية - الأنماط الفاخرة والألوان المميزة',
    aboutPt1: 'قماش فاخر', aboutPt2: 'مقاسات مريحة', aboutPt3: 'سعر عادل',
    trust1: 'ضمان استبدال القياس', trust1sub: 'اطلب باطمئنان', trust2: 'مدى المقاسات', trust3: '10+ قطع', trust4: 'على الطلبات الكبيرة', trust4v: 'شحن مجاني + خصم',
    shopKicker: 'المجموعة', shopTitle: 'كل المنتجات', shopNote: 'تيشيرت 35K · بنطرون 30K · قميص 25K · تراكسوت 70K دينار',
    gKicker: 'وعدنا', gTitle: 'ضمان الاستبدال في حال عدم مناسبة المقاس',
    gSub: 'اطلب باطمئنان — فريقنا يتواصل شخصيًا لتأكيد الطلب قبل الشحن',
    cKicker: 'تواصل', cTitle: 'رسالة واحدة تكفي',
    footAbout: `بدأت سايزمي من رؤية واضحة في العراق: سد الفجوة بين الأناقة العالمية والقياسات الخاصة\n\nفبينما يكتفي السوق بتوفير الموديلات التقليدية للأحجام الكبيرة، قررنا نحن تقديم ملابس عصرية من الماركات العالمية لتناسب اصحاب المقاسات الخاصة.\n\nنحن نجمع بين دقة التصميم الرقمي والخامات الفاخرة لضمان جودة تضاهي المنتجات العالمية.\n\nهدفنا هو تمكين كل رجل من ارتداء ما يحب، دون المساومة على الراحة أو القياس، مع تجربة تسوق إلكترونية ذكية وسهلة.`,
    footHelp: 'مساعدة', footHelp1: 'الأسعار: 25,000–70,000 د.ع حسب الفئة', footHelp2: 'التوصيل: 5,000 د.ع (العراق)', footHelp3: 'شحن مجاني عند 10 قطع فأكثر',
    footFollow: 'تابعنا',
    cartTitle: 'سلة المشتريات', sum: 'المجموع الكلي', disc: 'خصم الكمية (5,000/قطعة)', ship: 'كلفة التوصيل', total: 'الإجمالي',
    bulkHint: 'أضف 10 قطع أو أكثر للحصول على سعر 30,000 للقطعة + شحن مجاني.',
    checkout: 'إتمام الطلب',
    coTitle: 'إتمام الشراء', coCountry: 'الدولة', coName: 'الاسم الكامل *',
    coProv: 'المحافظة *', coArea: 'المدينة *', coAddr: 'المنطقة أو الحي والشارع *',
    coPhone: 'رقم الهاتف *', coPhoneNote: 'يجب أن يكون مرتبطًا بواتساب.',
    coNotes: 'ملاحظات (اختياري)', coPlace: 'تأكيد الطلب',
    coNotesPlaceholder: '(اختياري) يفضل كتابة الطول والوزن هنا لمساعدتنا في التأكد من دقة القياس المناسب لك',
    valName: 'يرجى إدخال الاسم الكامل',
    valProv: 'يرجى اختيار المحافظة',
    valArea: 'يرجى إدخال اسم المدينة أو المنطقة',
    valAddr: 'يرجى إدخال العنوان التفصيلي',
    valPhone: 'يرجى إدخال رقم الهاتف',
    valPhoneFmt: 'رقم الهاتف يجب أن يبدأ بـ 07 ويتكون من 11 رقماً',
    cfTitle: 'تم استلام طلبك', cfBody: (n) => `شكراً ${n}, فريق SizeMe سيتواصل معك قريبًا لتأكيد طلبك. ملاحظة: نوفّر ضمان استبدال في حال عدم مناسبة القياس.`,
    cfClose: 'إغلاق',
    addBag: 'أضف إلى السلة', selectSize: 'اختر المقاس', selectColor: 'اختر اللون', qty: 'الكمية',
    empty: 'سلتك فارغة.', remove: 'إزالة',
    wg: { '2XL': '95–105 كغ', '3XL': '105–115 كغ', '4XL': '115–125 كغ', '5XL': '125–140 كغ', '6XL': '140–155 كغ', '7XL': '155–175 كغ' },
    wgJeans: { '38': '75–85 كغ', '40': '85–95 كغ', '42': '95–110 كغ', '44': '110–125 كغ', '46': '125–140 كغ', '48': '140–155 كغ' },
    free: 'مجاني',
    filterBrand: 'الماركة', filterColor: 'اللون', filterAll: 'الكل',
    filterCat: 'الفئة', catAll: 'الكل', catTshirt: 'تي شيرت', catPolo: 'بولو', catShirt: 'قميص', catJeans: 'بنطرون', catTracksuit: 'تراكسوت',
    ratingKicker: 'تقييمات زبائننا', ratingScore: '4.9', ratingCount: 'من +143 زبون راضٍ',
    ratFabric: 'جودة القماش', ratSizes: 'صحة المقاسات', ratDelivery: 'سرعة التوصيل', ratService: 'خدمة العملاء',
    pageNext: 'التالي', pagePrev: 'السابق',
    noResults: 'لا توجد منتجات تطابق الفلتر المختار.',
    shopCountFn: (s, t) => `${s} من ${t} منتج`,
    bulkProgressFn: (n) => n >= 10 ? '🎉 سعر 30,000 للقطعة + شحن مجاني مفعّل!' : `أضف ${10 - n} قطعة للحصول على سعر 30,000 للقطعة وشحن مجاني`,
    bulkActiveBadge: 'مفعّل ✓', bulkPendingBadge: '10 قطع',
    footInteract: 'تفاعل معنا', footSuggBtn: 'شاركنا اقتراحك', footReviewsBtn: 'آراء الزبائن',
    footLinks: 'المساعدة ', footSizeGuide: 'دليل المقاسات', footFaq: 'الأسئلة الشائعة',
    footNewsletter: 'انضم إلى عائلة Sizeme',
    footNewsletterSub: 'سجل للحصول على اخر اخبارنا قبل الجميع',
    footNewsletterInput: 'بريدك الإلكتروني أو رقم الهاتف', footNewsletterBtn: 'إشترك',
    suggTitle: 'شاركنا اقتراحك', suggSub: 'اقتراحك يهمنا، سيتم حفظه ومراجعته بكل اهتمام',
    suggPlaceholder: 'اكتب اقتراحك هنا...', suggSend: 'إرسال',
    reviewsTitle: 'آراء الزبائن', reviewsEmpty: 'لا توجد صور reviews/',
    couponPlaceholder: 'كود الخصم', couponApply: 'تطبيق', couponRemove: 'إزالة',
    couponInvalid: 'الكود غير صحيح أو منتهي الصلاحية.', couponDisc: 'خصم الكوبون',
    couponApplied: (code, val) => `✓ ${code} — خصم ${val} مفعّل`,
    payTitle: 'طريقة الدفع',
    payCOD: 'الدفع عند الاستلام', payCODSub: 'ادفع عند استلام طلبك',
    payOnline: 'دفع إلكتروني آمن', payOnlineSub: 'قريباً', payOnlineBadge: 'قريباً',
    payWhatsApp: 'الدفع عند الاستلام',
    mbarLabel: 'السلة', mbarPcs: 'قطعة', mbarTotalLbl: 'المجموع', mbarBtn: 'عرض السلة',
    newBadge: 'جديد',
    sizeCalcBtn: 'احسب مقاسك', sizeCalcTitle: 'احسب مقاسك',
    scWeightLbl: 'الوزن (كغ)', scHeightLbl: 'الطول (سم) — اختياري', scCalcBtn: 'احسب'
  },
  en: {
    dir: 'ltr',
    bar1: 'Free shipping on orders of 10+ pieces · Special bulk discount · Sizes 2XL–7XL',
    bar2: 'Replacement guarantee if the size doesn\'t fit',
    navShop: 'Shop', navAbout: 'About', navContact: 'Contact',
    tagline: 'PREMIUM · PLUS SIZES',
    heroKicker: 'Est. Iraq · Specialized Sizes',
    heroTitle: 'Dressed Well. In Every Size.',
    heroSub: 'Premium brand T-shirts crafted for 2XL through 7XL — unified pricing, unified quality.',
    videoTitle: 'Our Brand Mission', videoHint: 'PLACE video/brand-mission.mp4',
    aboutKicker: 'Our Craft',
    aboutTitle: 'Premium Brand Clothing - Exclusive Patterns & Distinctive Sizes.',
    aboutPt1: 'FINE COTTON', aboutPt2: '2XL — 7XL', aboutPt3: 'FAIR PRICE',
    trust1: 'Size Guarantee', trust1sub: 'Order Confidently', trust2: 'Size Range', trust3: '10+ Pieces', trust4: 'On bulk orders', trust4v: 'Free Shipping',
    shopKicker: 'The Collection', shopTitle: 'All Products', shopNote: 'T-Shirt 35K · Jeans 30K · Shirt 25K · Tracksuit 70K IQD',
    gKicker: 'Promise', gTitle: "Replacement guarantee if the size doesn't fit.",
    gSub: 'Order with confidence — our team follows up on every order personally before dispatch.',
    cKicker: 'Reach Us', cTitle: "We're one message away.",
    footAbout: `Sizeme started with a clear vision in Iraq: to bridge the gap between global fashion and specialized plus sizes.\n\nWhile the market settles for providing traditional designs for larger sizes, we decided to offer modern clothing from international brands tailored for plus sizes.\n\nWe combine digital design precision with luxurious fabrics to ensure quality that rivals global products.\n\nOur goal is to empower every man to wear what he loves, without compromising on comfort or fit, through a smart and seamless online shopping experience.`,
    footHelp: 'Help', footHelp1: 'Prices: 25,000–70,000 IQD by category', footHelp2: 'Delivery: 5,000 IQD (Iraq)', footHelp3: 'Free shipping on 10+ pieces',
    footFollow: 'Follow',
    cartTitle: 'Your Bag', sum: 'Subtotal', disc: 'Bulk Discount (5K/piece)', ship: 'Delivery', total: 'Total',
    bulkHint: 'Add 10+ pieces to get 30,000 IQD/piece + free shipping.',
    checkout: 'CHECKOUT',
    coTitle: 'Checkout', coCountry: 'Country', coName: 'Full Name *',
    coProv: 'Province *', coArea: 'City / District *', coAddr: 'Street & Area *',
    coPhone: 'Phone *', coPhoneNote: 'Preferably linked to WhatsApp.',
    coNotes: 'Notes (optional)', coPlace: 'PLACE ORDER',
    coNotesPlaceholder: '(Optional) We recommend adding your height & weight to help us confirm the best size for you',
    valName: 'Please enter your full name',
    valProv: 'Please select your province',
    valArea: 'Please enter your city or district',
    valAddr: 'Please enter your full address',
    valPhone: 'Please enter your phone number',
    valPhoneFmt: 'Phone must start with 07 and be 11 digits',
    cfTitle: 'Order Received', cfBody: (n) => `Thank you ${n}, the SizeMe team will contact you shortly to confirm your order. Note: We provide a replacement guarantee if the size is not suitable.`,
    cfClose: 'CLOSE',
    addBag: 'Add to Bag', selectSize: 'Select Size', selectColor: 'Select Color', qty: 'Qty',
    empty: 'Your bag is empty.', remove: 'Remove',
    wg: { '2XL': '95–105 kg', '3XL': '105–115 kg', '4XL': '115–125 kg', '5XL': '125–140 kg', '6XL': '140–155 kg', '7XL': '155–175 kg' },
    wgJeans: { '38': '75–85 kg', '40': '85–95 kg', '42': '95–110 kg', '44': '110–125 kg', '46': '125–140 kg', '48': '140–155 kg' },
    free: 'Free',
    filterBrand: 'Brand', filterColor: 'Color', filterAll: 'All',
    filterCat: 'Category', catAll: 'All', catTshirt: 'T-Shirt', catPolo: 'Polo', catShirt: 'Shirt', catJeans: 'Jeans', catTracksuit: 'Tracksuit',
    ratingKicker: 'Customer Ratings', ratingScore: '4.9', ratingCount: 'From 143+ happy customers',
    ratFabric: 'Fabric Quality', ratSizes: 'True to Size', ratDelivery: 'Fast Delivery', ratService: 'Customer Service',
    pageNext: 'Next', pagePrev: 'Prev',
    noResults: 'No products match the selected filters.',
    shopCountFn: (s, t) => `${s} of ${t} products`,
    bulkProgressFn: (n) => n >= 10 ? '🎉 30,000 IQD/piece + free shipping unlocked!' : `Add ${10 - n} more pieces for 30K/piece & free shipping`,
    bulkActiveBadge: 'Active ✓', bulkPendingBadge: '10 pcs',
    footInteract: 'Interact', footSuggBtn: 'Share a Suggestion', footReviewsBtn: 'Customer Reviews',
    footLinks: ' HELP ', footSizeGuide: 'Size Guide', footFaq: 'FAQ',
    footNewsletter: 'Join the Sizeme Family',
    footNewsletterSub: 'Get exclusive collections and special sizes before anyone else',
    footNewsletterInput: 'Your email or phone number', footNewsletterBtn: 'Join',
    suggTitle: 'Share Your Suggestion', suggSub: 'Your message will be sent via WhatsApp.',
    suggPlaceholder: 'Write your suggestion here...', suggSend: 'Send',
    reviewsTitle: 'Customer Reviews', reviewsEmpty: 'No review photos yet. Add images to the reviews/ folder.',
    couponPlaceholder: 'Coupon code', couponApply: 'Apply', couponRemove: 'Remove',
    couponInvalid: 'Invalid or expired coupon code.', couponDisc: 'Coupon Discount',
    couponApplied: (code, val) => `✓ ${code} — ${val} off applied`,
    payTitle: 'Payment Method',
    payCOD: 'Cash on Delivery', payCODSub: 'Pay when you receive',
    payOnline: 'Secure Online Payment', payOnlineSub: 'Coming soon', payOnlineBadge: 'Soon',
    payWhatsApp: 'Cash on Delivery',
    mbarLabel: 'Cart', mbarPcs: 'pcs', mbarTotalLbl: 'Total', mbarBtn: 'View Bag',
    newBadge: 'NEW',
    sizeCalcBtn: 'Size Guide', sizeCalcTitle: 'Find Your Size',
    scWeightLbl: 'Weight (kg)', scHeightLbl: 'Height (cm) — optional', scCalcBtn: 'Calculate'
  },
  ku: {
    dir: 'rtl',
    bar1: 'گەیاندن بێبەرامبەر بۆ داواکاری ١٠ پارچە یان زیاتر · داشکاندن ٢٠٪ · قەبارەکان 2XL–7XL',
    bar2: 'گەرەنتی گۆڕینەوە ئەگەر قەبارەکە گونجاو نەبوو',
    navShop: 'فرۆشگا', navAbout: 'دەربارە', navContact: 'پەیوەندی',
    tagline: 'قياساتي تايبەت',
    heroKicker: 'لە عێراق · قەبارەی تایبەت',
    heroTitle: 'جلی جوان. بۆ هەموو قەبارەیەک.',
    heroSub: 'تیشێرتی مارکەی جیهانی بۆ قەبارەی 2XL تا 7XL — نرخی یەکسان، کوالێتی یەکسان.',
    videoTitle: 'بینینی ئێمە', videoHint: 'ڤیدیۆ دابنێ لە video/brand-mission.mp4',
    aboutKicker: 'پیشەی ئێمە',
    aboutTitle: 'تایبەتمەند لە جلوبەرگی مارکەی فاخر - نەخشی تایبەت و قەبارەی تایبەت.',
    aboutPt1: 'پەڕۆی فاخر', aboutPt2: '2XL — 7XL', aboutPt3: 'نرخی دادپەروەر',
    trust1: 'گەرەنتی گۆڕینەوە', trust1sub: 'بە دلنیاییەوە داوا بکە', trust2: 'قەبارە', trust3: '١٠+ پارچە', trust4: 'لەسەر داواکاری گەورە', trust4v: 'گەیاندن بێبەرامبەر',
    shopKicker: 'کۆمەڵە', shopTitle: 'هەموو بەرهەمەکان', shopNote: 'تی شێرت 35K · جینز 30K · کراس 25K · تراکسوت 70K د.ع',
    gKicker: 'بەڵێنمان', gTitle: 'گەرەنتی گۆڕینەوە ئەگەر قەبارەکە گونجاو نەبوو.',
    gSub: 'بە دڵنیاییەوە داوا بکە — تیمەکەمان پەیوەندیت پێوە دەکات پێش ناردن.',
    cKicker: 'پەیوەندی', cTitle: 'تەنها پەیامێک دوورین.',
    footAbout: `سایزمی لە دیدگایەکی ڕوونەوە لە عێراق دەستی پێکرد: پڕکردنەوەی کەلێنی نێوان مۆدێلی جیهانی و قەبارە تایبەتەکان.\n\nلە کاتێکدا بازاڕ تەنها مۆدێلە تەقلیدییەکان بۆ قەبارە گەورەکان دابین دەکات، ئێمە بڕیارمان دا جلوبەرگی سەردەمیانەی مارکە جیهانییەکان پێشکەش بکەین کە گونجاون بۆ قەبارە تایبەتەکان.\n\nئێمە وردبینی دیزاینی دیجیتاڵی و خامەی کوالێتی بەرز تێکەڵ دەکەین بۆ دەستەبەرکردنی کوالێتییەک کە هاوتای بەرهەمە جیهانییەکان بێت.\n\nئامانجی ئێمە ئەوەیە کە هەر پیاوێک بتوانێت ئەوەی حەزی لێیەتی بیپۆشێت، بەبێ ئەوەی دەستبەرداری ئاسوودەیی یان قەبارەکەی بێت، لەگەڵ ئەزموونێکی ئاسان و زیرەکی بازاڕکردنی ئۆنلاین.`,
    footHelp: 'یارمەتی', footHelp1: 'نرخەکان: ٢٥،٠٠٠–٧٠،٠٠٠ د.ع بەپێی جۆر', footHelp2: 'گەیاندن: ٥،٠٠٠ د.ع (عێراق)', footHelp3: 'گەیاندن بێبەرامبەر لەگەڵ ١٠ پارچە بۆ سەرەوە',
    footFollow: 'شوێنمان بکەوە',
    cartTitle: 'سەبەتەی تۆ', sum: 'کۆی بچووک', disc: 'داشکاندنی کۆمەڵ (٥٠٠٠/پارچە)', ship: 'گەیاندن', total: 'کۆی گشتی',
    bulkHint: '١٠ پارچە یان زیاتر زیاد بکە بۆ نرخی ٣٠،٠٠٠ بۆ هەر پارچەیەک + گەیاندن بێبەرامبەر.',
    checkout: 'تەواوکردن',
    coTitle: 'تەواوکردنی داواکاری', coCountry: 'وڵات', coName: 'ناوی تەواو *',
    coProv: 'پارێزگا *', coArea: 'شار / ناوچە *', coAddr: 'ناونیشانی تەواو *',
    coPhone: 'ژمارەی مۆبایل *', coPhoneNote: 'پێویستە بە واتساپ بەستراوە بێت.',
    coNotes: 'تێبینی (ئارەزوومەندانە)', coPlace: 'پشتڕاستکردنەوەی داواکاری',
    coNotesPlaceholder: '(ئارەزوومەندانە) باشتره درێژی و کێشت لێرە بنووسیت بۆ دیاریکردنی قەبارەی گونجاو',
    valName: 'تکایە ناوی تەواوت بنووسە',
    valProv: 'تکایە پارێزگاکەت هەڵبژێرە',
    valArea: 'تکایە ناوی شار یان ناوچە بنووسە',
    valAddr: 'تکایە ناونیشانی تەواو بنووسە',
    valPhone: 'تکایە ژمارەی مۆبایلت بنووسە',
    valPhoneFmt: 'ژمارەکە دەبێت بە 07 دەست پێ بکات و ١١ ژمارە بێت',
    cfTitle: 'داواکاریت وەرگیرا', cfBody: (n) => `سوپاس ${n}, تیمی SizeMe بەم زووانە پەیوەندیت پێوە دەکات بۆ پشتڕاستکردنەوەی داواکاریت. تێبینی: گەرەنتی گۆڕینەوە لەبەردەستە ئەگەر قەبارەکە گونجاو نەبوو.`,
    cfClose: 'داخستن',
    addBag: 'زیادکردن بۆ سەبەتە', selectSize: 'قەبارە هەڵبژێرە', selectColor: 'ڕەنگ هەڵبژێرە', qty: 'ژمارە',
    empty: 'سەبەتەکەت بەتاڵە.', remove: 'سڕینەوە',
    wg: { '2XL': '٩٥–١٠٥ کیلۆ', '3XL': '١٠٥–١١٥ کیلۆ', '4XL': '١١٥–١٢٥ کیلۆ', '5XL': '١٢٥–١٤٠ کیلۆ', '6XL': '١٤٠–١٥٥ کیلۆ', '7XL': '١٥٥–١٧٥ کیلۆ' },
    wgJeans: { '38': '٧٥–٨٥ کیلۆ', '40': '٨٥–٩٥ کیلۆ', '42': '٩٥–١١٠ کیلۆ', '44': '١١٠–١٢٥ کیلۆ', '46': '١٢٥–١٤٠ کیلۆ', '48': '١٤٠–١٥٥ کیلۆ' },
    free: 'بێبەرامبەر',
    filterBrand: 'مارکە', filterColor: 'ڕەنگ', filterAll: 'هەموو',
    filterCat: 'جۆر', catAll: 'هەموو', catTshirt: 'تی شێرت', catPolo: 'پۆلۆ', catShirt: 'کراس', catJeans: 'جینز', catTracksuit: 'تراکسوت',
    ratingKicker: 'هەڵسەنگاندنی کڕیاران', ratingScore: '4.9', ratingCount: 'لە +١٤٣ کڕیارى دلخۆش',
    ratFabric: 'کوالیتی پەڕەکە', ratSizes: 'ڕاستی سایز', ratDelivery: 'خێرایی گەیاندن', ratService: 'خزمەتگوزارى',
    pageNext: 'دواتر', pagePrev: 'پێشتر',
    noResults: 'هیچ بەرهەمێک نەدۆزرایەوە.',
    shopCountFn: (s, t) => `${s} لە ${t} بەرهەم`,
    bulkProgressFn: (n) => n >= 10 ? '🎉 نرخی ٣٠،٠٠٠ بۆ هەر پارچەیەک + گەیاندن بێبەرامبەر چالاکە!' : `${10 - n} پارچەی تر زیاد بکە بۆ نرخی ٣٠،٠٠٠`,
    bulkActiveBadge: 'چالاکە ✓', bulkPendingBadge: '١٠ پارچە',
    footInteract: 'پەیوەندی', footSuggBtn: 'پێشنیازت بنێرە', footReviewsBtn: 'بۆچوونی کڕیار',
    footLinks: 'بەستەرەکان', footSizeGuide: 'ڕێنمایی قەبارە', footFaq: 'پرسیارە باوەکان',
    footNewsletter: 'بەیەک بپەیوەند بە Sizeme',
    footNewsletterSub: 'کۆمەڵە تایبەتەکان و قەبارەی تایبەت پێشتر وەربگرە',
    footNewsletterInput: 'ئیمەیلەکەت یان ژمارەی مۆبایلەکەت', footNewsletterBtn: 'بەشداری',
    suggTitle: 'پێشنیازت بنێرە', suggSub: 'پێشنیازەکەت ڕاستەوخۆ بە واتساپ دەنێردرێت.',
    suggPlaceholder: 'پێشنیازەکەت لێرە بنووسە...', suggSend: 'ناردن',
    reviewsTitle: 'بۆچوونی کڕیار', reviewsEmpty: 'هێشتا وێنەی بۆچوون نییە. وێنەکان لە reviews/ دابنێ.',
    couponPlaceholder: 'کۆدی داشکاندن', couponApply: 'جێبەجێکردن', couponRemove: 'سڕینەوە',
    couponInvalid: 'کۆدەکە هەڵەیە یان کاتی تەواو بووە.', couponDisc: 'داشکاندنی کۆپۆن',
    couponApplied: (code, val) => `✓ ${code} — داشکاندن ${val} چالاکە`,
    payTitle: 'شێوازی پارەدان',
    payCOD: 'پارەدان لە کاتی وەرگرتن', payCODSub: 'پارەدان لەکاتی گەیاندن',
    payOnline: 'پارەدانی ئەلیکترۆنی', payOnlineSub: 'بەم زووانە', payOnlineBadge: 'بەم زووانە',
    payWhatsApp: 'پارەدان لە کاتی وەرگرتن',
    mbarLabel: 'سەبەتە', mbarPcs: 'دانە', mbarTotalLbl: 'کۆی گشتی', mbarBtn: 'سەبەتەکەت ببینە',
    newBadge: 'نوێ',
    sizeCalcBtn: 'قەبارەکەت بزانە', sizeCalcTitle: 'قەبارەکەت بزانە',
    scWeightLbl: 'کێشە (کیلۆ)', scHeightLbl: 'بەرزی (سم) — ئارەزوومەندانە', scCalcBtn: 'حیساب بکە'
  }
};

export const C = {
  BLK: { n: 'Black', h: '#111111' },
  WHT: { n: 'White', h: '#FAFAFA' },
  DNV: { n: 'Dark Navy', h: '#091E5B' },
  RBL: { n: 'Royal Blue', h: '#1E3FB5' },
  BRN: { n: 'Brown', h: '#4A2C1D' },
  BRG: { n: 'Burgundy', h: '#732020' },
  CHR: { n: 'Charcoal', h: '#2D2D2D' },
  TPE: { n: 'Taupe', h: '#8E8475' },
  OLV: { n: 'Olive', h: '#3D4A2A' },
};

export const TOTAL_PRODUCTS = 36;

export const PRODUCTS_META = {
  1: { sku: 'LA-01', imgKey: 'lacoste-e33', brand: 'LACOSTE', sub: 'E33 Flag', colors: [C.BLK, C.WHT, C.OLV], status: 'best-seller' },
  2: { sku: 'PO-02', imgKey: 'polo', brand: 'U.S. POLO ASSN', sub: 'Polo Classic', colors: [C.BLK, C.WHT, C.RBL, C.TPE], status: 'best-seller' },
  3: { sku: 'GI-03', imgKey: 'givenchy', brand: 'GIVENCHY', sub: 'Paris', colors: [C.BLK, C.WHT, C.BRN], status: '' },
  4: { sku: 'OW-04', imgKey: 'off-white', brand: 'OFF-WHITE', sub: 'Hand Logo', colors: [C.BLK, C.WHT, C.RBL], status: '' },
  5: { sku: 'HU-05', imgKey: 'hugo', brand: 'HUGO', sub: 'Bold Logo', colors: [C.BLK, C.WHT, C.DNV], status: '' },
  6: { sku: 'LA-07', imgKey: 'lacoste-1927', brand: 'LACOSTE', sub: '1927 Heritage', colors: [C.BLK, C.WHT], status: 'best-seller' },
  7: { sku: 'BA-08', imgKey: 'balmain', brand: 'BALMAIN', sub: 'Paris', colors: [C.BLK, C.WHT, C.OLV, C.BRG], status: '' },
  8: { sku: 'AL-09', imgKey: 'alo', brand: 'ALO', sub: 'basic', colors: [C.BLK, C.DNV, C.CHR, C.BRN], status: '' },
  9: { sku: 'PR-10', imgKey: 'prada', brand: 'PRADA', sub: 'Milano', colors: [C.BLK, C.WHT, C.BRN, C.CHR], status: '' },
  10: { sku: 'BU-11', imgKey: 'burberry', brand: 'BURBERRY', sub: 'Knight', colors: [C.BLK, C.WHT, C.CHR], status: '' },
  11: { sku: 'TO-12', imgKey: 'tommy', brand: 'TOMMY JEANS', sub: 'Graffiti', colors: [C.BLK, C.WHT, C.CHR], status: '' },
  12: { sku: 'CK-13', imgKey: 'ck', brand: 'CALVIN KLEIN', sub: 'CK Monogram', colors: [C.BLK, C.WHT], status: '' },
  13: { sku: 'KI-14', imgKey: 'kiton', brand: 'KITON', sub: 'Napoli', colors: [C.BLK, C.WHT], status: '' },
  14: { sku: 'LO-15', imgKey: 'loewe', brand: 'LOEWE', sub: 'Madrid 1846', colors: [C.BLK, C.WHT], status: '' },
  15: { sku: 'LV-16', imgKey: 'lv', brand: 'LOUIS VUITTON', sub: 'Paris', colors: [C.BLK, C.WHT, C.TPE], status: 'best-seller' },
  16: { sku: 'KI-17', imgKey: 'kiton-small', brand: 'KITON', sub: 'Small Logo', colors: [C.BLK, C.WHT, C.CHR], status: '' },
  17: { sku: 'CK-18', imgKey: 'calvin-klein', brand: 'CALVIN KLEIN', sub: 'Classic', colors: [C.BLK, C.WHT, C.OLV, C.BRN], status: '' },
  18: { sku: 'BO-19', imgKey: 'boos', brand: 'BOSS', sub: 'sun logo', colors: [C.BLK, C.WHT, C.DNV], status: '' },
  19: { sku: 'ES-20', imgKey: 'essentials', brand: 'ESSENTIALS', sub: 'NBA', colors: [C.BLK, C.WHT, C.TPE], status: '' },
  20: { sku: 'PO-21', imgKey: 'u-s-polo', brand: 'U.S. POLO ASSN', sub: 'Assn horse', colors: [C.BLK, C.WHT, C.OLV], status: '' },
  21: { sku: 'HE-22', imgKey: 'hermes', brand: 'HERMÈS', sub: 'horse Paris', colors: [C.BLK, C.WHT], status: 'best-seller' },
  22: { sku: 'BA-23', imgKey: 'balenciaga', brand: 'BALENCIAGA', sub: 'balenc shop', colors: [C.BLK, C.WHT, C.RBL], status: '' },
  23: { sku: 'SU-24', imgKey: 'supreme', brand: 'SUPREME', sub: 'Earth Logo', colors: [C.BLK, C.WHT, C.CHR], status: '' },
  24: { sku: 'HE-25', imgKey: 'hermes-h', brand: 'HERMÈS', sub: 'Lines Logo', colors: [C.BLK, C.WHT], status: '' },
  25: { sku: 'MA-26', imgKey: 'massimo-dutti', brand: 'MASSIMO DUTTI', sub: 'since 1985', colors: [C.BLK, C.WHT, C.BRN, C.CHR], status: '' },
  26: { sku: 'LV-26', imgKey: 'lv', brand: 'LOUIS VUITTON', sub: 'umbrellas', colors: [C.BLK, C.WHT, C.TPE], status: 'new' },
  27: { sku: 'PP-27', imgKey: 'polo-plus', brand: 'POLO PLUS', sub: 'Classic Fit', colors: [C.BLK, C.WHT, C.RBL], status: 'new', category: 'polo', catSeq: '01' },
  28: { sku: 'HE-29', imgKey: 'hermes-ss', brand: 'HERMÈS', sub: 'Sport', colors: [C.BLK, C.WHT, C.BRN], status: 'new', category: 'tracksuit', catSeq: '01' },
  29: { sku: 'BA-27', imgKey: 'balenciaga', brand: 'BALENCIAGA', sub: 'New Collection', colors: [C.BLK, C.WHT, C.CHR], status: 'new', category: 'tshirt', catSeq: '27' },
  30: { sku: 'SU-28', imgKey: 'supreme', brand: 'SUPREME', sub: 'New Collection', colors: [C.BLK, C.WHT], status: 'new', category: 'tshirt', catSeq: '28' },
  31: { sku: 'LV-29', imgKey: 'lv', brand: 'LOUIS VUITTON', sub: 'New Collection', colors: [C.BLK, C.WHT, C.TPE], status: 'new', category: 'tshirt', catSeq: '29' },
  32: { sku: 'JJ-30', imgKey: 'jackjones', brand: 'JACK & JONES', sub: 'New Collection', colors: [C.BLK, C.WHT], status: 'new', category: 'tshirt', catSeq: '30' },
  33: { sku: 'LV-31', imgKey: 'lv', brand: 'LOUIS VUITTON', sub: 'New Collection', colors: [C.BLK, C.WHT, C.DNV], status: 'new', category: 'tshirt', catSeq: '31' },
  34: { sku: 'BU-35', imgKey: 'burberry-new', brand: 'BURBERRY', sub: 'Classic', colors: [C.BLK, C.WHT], status: 'new', category: 'shirt', catSeq: '01' },
  35: { sku: 'CA-36', imgKey: 'cargo-army', brand: 'CARGO', sub: 'Army Style', colors: [C.OLV, C.TPE], status: 'new', category: 'jeans', catSeq: '01' },
  36: { sku: 'CA-37', imgKey: 'cargo-army', brand: 'CARGO', sub: 'Army Black', colors: [C.BLK, C.CHR], status: 'new', category: 'jeans', catSeq: '02' },
};

export const PRODUCTS = Array.from({ length: TOTAL_PRODUCTS }, (_, i) => {
  const n = TOTAL_PRODUCTS - i;
  const prefix = String(n).padStart(2, '0');
  const m = PRODUCTS_META[n] || { sku: `P-${prefix}`, imgKey: 'product', brand: 'SIZEME', sub: 'New', colors: [C.BLK] };
  return {
    id: `p${n}`,
    prefix,
    catSeq: m.catSeq || null,
    sku: m.sku || `P-${prefix}`,
    imgKey: m.imgKey,
    brand: m.brand,
    sub: m.sub,
    colors: m.colors,
    category: m.category || 'tshirt',
    status: m.status || '',
  };
});

export const COUPONS = [
  { code: 'welcome', type: 'percent', value: 15, expires: '2026-12-31' },
  { code: 'SIZEME2026', type: 'percent', value: 5, expires: '2026-12-31' },
  { code: 'VIP15', type: 'percent', value: 10, expires: '2026-09-30' },
  { code: 'WELCOME', type: 'fixed', value: 5000, expires: null },
];
